[book]
authors = ["JP Posma", "Paras Sanghavi", "Hernan Saez", "Dmitry Panin"]
language = "en"
multilingual = false
src = "src"
title = "Zaplib docs"

[output.html]
git-repository-url="https://github.com/Zaplib/zaplib"
edit-url-template = "https://github.com/Zaplib/zaplib/edit/main/zaplib/docs/{path}"
additional-css = ["theme/css/custom.css"]

[output.html.print]
enable = false