[package]
name = "tutorial_3d_rendering_step3"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
zaplib = { path = "../../../main" }
zaplib_components = { path = "../../../components" }
