[package]
name = "example_lightning"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
zaplib = { path="../../main" }
zaplib_components = { path="../../components" }

[features]
disable-interaction=["zaplib/disable-fonts"]
