name: CI
on: [push]
jobs:
  build_web_ci:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:0bbef21ebbbdcdd42c46e85118bcddb2a9b668eb9cb027d46f96989b97117baf
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: zaplib/scripts/ci/build_web_ci.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  checks_for_all_targets_debug:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:0bbef21ebbbdcdd42c46e85118bcddb2a9b668eb9cb027d46f96989b97117baf
    steps:
      - uses: actions/checkout@v2
      - run: zaplib/scripts/ci/checks_for_all_targets_debug.sh
  checks_for_all_targets_release:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:0bbef21ebbbdcdd42c46e85118bcddb2a9b668eb9cb027d46f96989b97117baf
    steps:
      - uses: actions/checkout@v2
      - run: zaplib/scripts/ci/checks_for_all_targets_release.sh
  debug_builds:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:0bbef21ebbbdcdd42c46e85118bcddb2a9b668eb9cb027d46f96989b97117baf
    steps:
      - uses: actions/checkout@v2
      - run: zaplib/scripts/ci/debug_builds.sh
  lint:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:0bbef21ebbbdcdd42c46e85118bcddb2a9b668eb9cb027d46f96989b97117baf
    steps:
      - uses: actions/checkout@v2
      - run: zaplib/scripts/ci/lint.sh
  release_builds:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:0bbef21ebbbdcdd42c46e85118bcddb2a9b668eb9cb027d46f96989b97117baf
    steps:
      - uses: actions/checkout@v2
      - run: zaplib/scripts/ci/release_builds.sh
  rust_nightly_build:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:0bbef21ebbbdcdd42c46e85118bcddb2a9b668eb9cb027d46f96989b97117baf
    steps:
      - uses: actions/checkout@v2
      - run: zaplib/scripts/ci/rust_nightly_build.sh
  tests:
    runs-on: ubuntu-latest
    container:
      image: janpaul123/zaplib-ci@sha256:0bbef21ebbbdcdd42c46e85118bcddb2a9b668eb9cb027d46f96989b97117baf
    steps:
      - uses: actions/checkout@v2
      - run: zaplib/scripts/ci/tests.sh
